server:
  port: 5000
spring:
  application:
    name: fangchy-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: keyId
    access-key-secret: keySecret
    bucket-domain: domain
    bucket-name: name
    end-point: endpoint