server:
  port: 4000
spring:
  application:
    name: fangchy-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka